<?php

namespace admin\EconomatBundle\Entity;

use Doctrine\ORM\EntityRepository;
use admin\UserBundle\Types\TypeEtat;

/**
 * CategorieRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieProduitRepository extends EntityRepository
{
    
    use \admin\EconomatBundle\EntityModel\entityTrait;
    
    /**
     * Retourne un ou tous les categories si $idCategorie = 0.
     *
     * @param int $idCategorie
     *
     * @return array
     */
    public function getAllOrOneCategorie($idCategorie=0)
    {
        $idCategorieQuery = (int) $idCategorie;
        $qb = $this->createQueryBuilder('p')
                ->where('p.etat != '.TypeEtat::SUPPRIME);
              

        return $qb->getQuery()->getResult();
    }

    /**
     * Retourne tous les categories.
     *
     * @return type
     */
    public function getAllCategorieProduit()
    {
        $qb = $this->createQueryBuilder('p')
                ->where('p.etat != '.TypeEtat::SUPPRIME)
                ->orwhere('p.type != 4');
  

        return $qb->getQuery()->getResult();
    }
    /**
     * Retourne tous les categories.
     *
     * @return type
     */
    public function getAllCategorieLieProduit()
    {
        $qb = $this->createQueryBuilder('p')
                ->where('p.type != '.TypeEtat::SUPPRIME)
                ->orwhere('p.type != 4')
                ->orwhere('p.type != 3');
  

        return $qb->getQuery()->getResult();
    }
    
    /**
     * Retourne tous les categories.
     *
     * @return type
     */
    public function getAllCategorieLieProduitAutres()
    {
        $sql =  ' SELECT  p'
                   .' FROM '.$this->stockBundle.'CategorieProduit p '               
                   .' WHERE  p.etat = :etat '
                   .' ORDER BY p.nom DESC';
            $query = $this->_em->createQuery($sql);
            $query->setParameter('etat', 6);
            
            
            return $query->getResult();
   }
    
    
    public function getFournCategorie($fournisseur) {
        
            $sql =  ' SELECT DISTINCT c.id, c.nom '
                   .' FROM '.$this->stockBundle.'Produit p inner join p.fournisseur f '
                   .'       inner join p.categorie c '
                   .' WHERE  f.id = :fid '
                   .' ORDER BY c.nom DESC';

            $query = $this->_em->createQuery($sql);
            $query->setParameter('fid', $fournisseur);
            return $query->getResult();
    }
    
    
}
