<?php

namespace admin\EconomatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends EntityRepository {

    public function getInformationCommande($code) {

        $qb = $this->createQueryBuilder('c')
                ->where('c.codeCommande = \'' . $code . '\'');
        return $qb->getQuery()->getResult();
    }

    public function getClientCommande($id) {

          $query = $this->_em->createQuery(
                        'SELECT c,a
                        FROM adminStockBundle:Commande c INNER JOIN c.abonne a
                        WHERE c.id = :id'
                            )->setParameter('id',$id );
          return  $query->getResult();
    }
    
    public function getLigneCommande($id) {

          $query = $this->_em->createQuery(
                        'SELECT l,c
                        FROM adminStockBundle:LigneCommande l INNER JOIN l.commande c
                        WHERE c.id = :id'
                            )->setParameter('id',$id );
          
          return  $query->getResult();
          
    }
    
    public function getListeCommandeParType($type) {

          $query = $this->_em->createQuery(
                        'SELECT c
                        FROM adminStockBundle:Commande c
                        WHERE c.typeCommande = :typeCommande'
                            )->setParameter('typeCommande',$type );
          return  $query->getResult();
    }
    
    public function getOneCommande($id){
        
        $qb = $this->createQueryBuilder('c')
		   ->select('c')			
                   ->where('c.id = '.$id);
        return $qb->getQuery()->getResult();
    }
       
}
