<?php

namespace admin\EconomatBundle\Entity;

use admin\UserBundle\Types\TypeEtat;

/**
 * FournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseurRepository extends \Doctrine\ORM\EntityRepository
{
    
        /**
     * Retourne tous les fournisseurs.
     *
     * @return type
     */
    public function getAllFournisseur()
    {
        $qb = $this->createQueryBuilder('r')
                ->where('r.etatFournisseur != '.TypeEtat::SUPPRIME)
                ->orderBy('r.id', 'ASC');

        return $qb->getQuery()->getResult();
    }

        /**
     * Retourne un fournisseur.
     *
     * @return type
     */
    public function getOneFournisseur($id)
    {
        $qb = $this->createQueryBuilder('r')
		->select('r,i')         
                ->leftJoin('r.images', 'i')
                ->where('r.id = '.$id)
                ->orderBy('r.id', 'ASC');

        return $qb->getQuery()->getResult();
    }	
	
}
