<?php

namespace admin\EconomatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LigneCommandeTmpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneCommandeTmpRepository extends EntityRepository
{
    
    use \admin\EconomatBundle\EntityModel\entityTrait;

    public function allLigneCommandeTmp($prdt,$cde,$idLine) {
        
            $tab = array();
            $tab['lid'] =$idLine;
            $tab['prdt'] = $prdt;
            $tab['cde'] = $cde;
            
            $sql =  ' SELECT l.id AS nbre '
                   .' FROM '.$this->stockBundle.'LigneCommandeTmp l '
                   .' WHERE  l.id != :lid  AND l.commandeTmp = :cde and l.produit = :prdt ';

            $query = $this->_em->createQuery($sql);
            $query->setParameters($tab);
            
            try {
                $res = $query->getSingleScalarResult();
            } catch (\Doctrine\ORM\NoResultException $e) {
                $res = 0;
            }
            
            return $res;
    }
    
}
