<?php

namespace admin\EconomatBundle\Entity;

use admin\UserBundle\Types\TypeEtat;

use Doctrine\ORM\EntityRepository;

/**
 * VilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleRepository extends EntityRepository
{
            /**
     * Retourne tous les profils.
     *
     * @return type
     */
    public function getAllVille()
    {
        $qb = $this->createQueryBuilder('r')
                ->where('r.etatVille != '.TypeEtat::SUPPRIME)
                ->orderBy('r.id', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
