<?php

namespace admin\ScolariteBundle\Entity;
use \admin\UserBundle\Types\TypeEtat;

/**
 * AnneeScolaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnneeScolaireRepository extends \Doctrine\ORM\EntityRepository
{
    
          /*
     * Retourne un ou tous les profils si $idAnneeScolaire = 0
     * @param int $idAnneeScolaire
     * @return array
     */
    public function getAllOrOneAnneeScolaire($idAnneeScolaire) {
        $idAnneeScolaireQuery = (int) $idAnneeScolaire;
        $qb = $this->createQueryBuilder('p')
                ->where('p.etatAnneeScolaire != ' . TypeEtat::SUPPRIME)
                ;
        if($idAnneeScolaire > 0){
            $qb->andWhere('p.id =:idAnneeScolaire')
                    ->setParameter('idAnneeScolaire', $idAnneeScolaireQuery);
            
        }
        return $qb->getQuery()->getResult();
    }
    
    /*
     * Retourne tous les profils
     * @return type
     */
    public function getAllAnneeScolaire() {
        $qb = $this->createQueryBuilder('e')
                ->where('e.etatAnneeScolaire != ' . TypeEtat::SUPPRIME);
               // ->orderBy('e.typeAnneeScolaire', 'ASC');
        return $qb->getQuery()->getResult();
    }
}
