<?php

namespace admin\ScolariteBundle\Entity;

/**
 * ConcernerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcernerRepository extends \Doctrine\ORM\EntityRepository
{
}
