<?php

namespace admin\ScolariteBundle\Entity;
use \admin\UserBundle\Types\TypeEtat;
/**
 * DecoupageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecoupageRepository extends \Doctrine\ORM\EntityRepository
{
    
    use \admin\UserBundle\ControllerModel\paramUtilTrait;
         /*
     * Retourne un ou tous les decoupages si $idDecoupage = 0
     * @param int $idDecoupage
     * @return array
     */
    public function getAllOrOneDecoupage($idDecoupage) {
        $idDecoupageQuery = (int) $idDecoupage;
        $qb = $this->createQueryBuilder('p')
                ->where('p.etatDecoupage != ' . TypeEtat::SUPPRIME)
                ;
        if($idDecoupage > 0){
            $qb->andWhere('p.id =:idDecoupage')
                    ->setParameter('idDecoupage', $idDecoupageQuery);
            
        }
        return $qb->getQuery()->getResult();
    }
    
    /*
     * Retourne tous les decoupages
     * @return type
     */
    public function getAllDecoupage() {
        $qb = $this->createQueryBuilder('e')
                ->where('e.etatDecoupage != ' . TypeEtat::SUPPRIME);
               // ->orderBy('e.typeDecoupage', 'ASC');
        return $qb->getQuery()->getResult();
    }
    
    /*
     * Retourne tous les decoupages
     * @return type
     */
    public function getAllActifDecoupage() {
        $qb = $this->createQueryBuilder('e')
                ->where('e.etatDecoupage = ' . TypeEtat::ACTIF);
               // ->orderBy('e.typeDecoupage', 'ASC');
        return $qb->getQuery()->getResult();
    }
     public function getDecoupageActifClasse($idClasse) {
     $sql =  ' SELECT DISTINCT d.id'
                   .' FROM '.$this->scolariteBundle.'Decoupage d '
                   .' INNER JOIN d.typedecoupage t '
                   .' INNER JOIN t.concerners c '
                   .' INNER JOIN c.enseignement e '
                   .' INNER JOIN e.filieres f '
                   .' INNER JOIN f.classes cl '
                   .' WHERE  d.etatDecoupage = :cid and cl.id =:idClasse'
                  // .' ORDER BY m.libelleMatiere DESC'
                    ;

            $query = $this->_em->createQuery($sql);
            $query->setParameters(array('cid'=> 1, 'idClasse'=>$idClasse));
            return $query->getResult();
    } 
	
     public function getDecoupageClasse($idClasse) {
     $sql =  ' SELECT DISTINCT d.id,d.libelleDecoupage '
                   .' FROM '.$this->scolariteBundle.'Decoupage d '
                   .' INNER JOIN d.typedecoupage t '
                   .' INNER JOIN t.concerners c '
                   .' INNER JOIN c.enseignement e '
                   .' INNER JOIN e.filieres f '
                   .' INNER JOIN f.classes cl '
                   .' WHERE  cl.id =:idClasse'
                  // .' ORDER BY m.libelleMatiere DESC'
                    ;

            $query = $this->_em->createQuery($sql);
            $query->setParameters(array( 'idClasse'=>$idClasse));
            return $query->getResult();
    } 	
    
}
