<?php

namespace admin\ScolariteBundle\Entity;
use \admin\UserBundle\Types\TypeEtat;

/**
 * DegreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DegreRepository extends \Doctrine\ORM\EntityRepository
{
     /*
     * Retourne un ou tous les profils si $idDegre = 0
     * @param int $idDegre
     * @return array
     */
    public function getAllOrOneDegre($idDegre) {
        $idDegreQuery = (int) $idDegre;
        $qb = $this->createQueryBuilder('p')
                ->where('p.etatDegre != ' . TypeEtat::SUPPRIME)
                ;
        if($idDegre > 0){
            $qb->andWhere('p.id =:idDegre')
                    ->setParameter('idDegre', $idDegreQuery);
            
        }
        return $qb->getQuery()->getResult();
    }
    
    /*
     * Retourne tous les profils
     * @return type
     */
    public function getAllDegre() {
        $qb = $this->createQueryBuilder('e')
                ->where('e.etatDegre != ' . TypeEtat::SUPPRIME);
               // ->orderBy('e.typeDegre', 'ASC');
        return $qb->getQuery()->getResult();
    }    
    
    /*
     * Retourne tous les profils
     * @return type
     */
    public function getAllActifDegre() {
        $qb = $this->createQueryBuilder('e')
                ->where('e.etatDegre = ' . TypeEtat::ACTIF);
               // ->orderBy('e.typeDegre', 'ASC');
        return $qb->getQuery()->getResult();
    }    
    
}
