<?php

namespace admin\ScolariteBundle\Entity;

/**
 * DetailPresenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailPresenceRepository extends \Doctrine\ORM\EntityRepository
{
}
