<?php

namespace admin\ScolariteBundle\Entity;

/**
 * EcolageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcolageRepository extends \Doctrine\ORM\EntityRepository
{
}
