<?php

namespace admin\ScolariteBundle\Entity;
use \admin\UserBundle\Types\TypeEtat;

/**
 * EnseignementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnseignementRepository extends \Doctrine\ORM\EntityRepository
{
        /*
     * Retourne un ou tous les profils si $idEnseignement = 0
     * @param int $idEnseignement
     * @return array
     */
    public function getAllOrOneEnseignement($idEnseignement) {
        $idEnseignementQuery = (int) $idEnseignement;
        $qb = $this->createQueryBuilder('p')
                ->where('p.etatEnseignement != ' . TypeEtat::SUPPRIME)
                ;
        if($idEnseignement > 0){
            $qb->andWhere('p.id =:idEnseignement')
                    ->setParameter('idEnseignement', $idEnseignementQuery);
            
        }
        return $qb->getQuery()->getResult();
    }
    
    /*
     * Retourne tous les profils
     * @return type
     */
    public function getAllEnseignement() {
        $qb = $this->createQueryBuilder('e')
                ->where('e.etatEnseignement != ' . TypeEtat::SUPPRIME);
               // ->orderBy('e.typeEnseignement', 'ASC');
        return $qb->getQuery()->getResult();
    }
    
    
    /*
     * Retourne tous les profils
     * @return type
     */
    public function getAllActifEnseignement() {
        $qb = $this->createQueryBuilder('e')
                ->where('e.etatEnseignement = ' . TypeEtat::ACTIF);
               // ->orderBy('e.typeEnseignement', 'ASC');
        return $qb->getQuery()->getResult();
    }
}
