<?php

namespace admin\ScolariteBundle\Entity;

/**
 * EpreuveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpreuveRepository extends \Doctrine\ORM\EntityRepository
{
      use \admin\UserBundle\ControllerModel\paramUtilTrait;
    /**
     * Retourne un ou tous les epreuves si $idEpreuve = 0
     * @param int $idEpreuve
     * @return array
     */
    public function getAllOrOneEpreuve($idEpreuve) {
        $idEpreuveQuery = (int) $idEpreuve;
        $qb = $this->createQueryBuilder('p')
                ->where('p.etatEpreuve != ' . TypeEtat::SUPPRIME)
                ;
        if($idEpreuve > 0){
            $qb->andWhere('p.id =:idEpreuve')
                    ->setParameter('idEpreuve', $idEpreuveQuery);
            
        }
        return $qb->getQuery()->getResult();
    }
    
    /*
     * Retourne tous les epreuves
     * @return type
     */
    //    public function getAllEpreuve($estEns) {
    //        $qb = $this->createQueryBuilder('e')
    //                ->where('e.etatEpreuve != ' . TypeEtat::SUPPRIME);
    //               // ->orderBy('e.typeEpreuve', 'ASC');
    //        return $qb->getQuery()->getResult();
    //    }
    public function getAllEpreuve($idclasse) {
        $dql = "SELECT e FROM " . $this->scolariteBundle . "Epreuve e INNER JOIN e.classes c "
             . " WHERE c.id =:idclasse ";

        $query = $this->_em->createQuery($dql);
        $query->setParameter('idclasse', $idclasse);

        return $query->getResult();
    }     
    
    /*
     * Retourne tous les epreuves
     * @return type
     */
    public function getAllActifEpreuve() {
        $qb = $this->createQueryBuilder('e')
                ->where('e.etatEpreuve = ' . TypeEtat::ACTIF);
               // ->orderBy('e.typeEpreuve', 'ASC');
        return $qb->getQuery()->getResult();
    }
    
}
