<?php

namespace admin\ScolariteBundle\Entity;

/**
 * EstEnseigneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstEnseigneRepository extends \Doctrine\ORM\EntityRepository
{
}
