<?php

namespace admin\ScolariteBundle\Entity;

/**
 * EstParentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstParentRepository extends \Doctrine\ORM\EntityRepository
{
     use \admin\UserBundle\ControllerModel\paramUtilTrait;
    public function getEleveTuteur($idtuteur) {
        $dql = "SELECT e.id,el.id as idel, el.nom, el.prenoms, el.titreImage FROM " . $this->scolariteBundle . "EstParent e "
                . " INNER JOIN e.utilisateur u "
                . " INNER JOIN e.eleve el "
                . "WHERE u.id =:id and e.etatEstParent =:etat ";
       // var_dump($idtuteur);exit;
        $query = $this->_em->createQuery($dql);
        $query->setParameter('etat',3);
        $query->setParameter('id', $idtuteur);

        return $query->getResult();
    }
}
