<?php

namespace admin\ScolariteBundle\Entity;
use \admin\UserBundle\Types\TypeEtat;

/**
 * EtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementRepository extends \Doctrine\ORM\EntityRepository
{
        /*
     * Retourne un ou tous les profils si $idEtablissement = 0
     * @param int $idEtablissement
     * @return array
     */
    public function getAllOrOneEtablissement($idEtablissement) {
        $idEtablissementQuery = (int) $idEtablissement;
        $qb = $this->createQueryBuilder('p')
                ->where('p.etatEtablissement != ' . TypeEtat::SUPPRIME)
                ;
        if($idEtablissement > 0){
            $qb->andWhere('p.id =:idEtablissement')
                    ->setParameter('idEtablissement', $idEtablissementQuery);
            
        }
        return $qb->getQuery()->getResult();
    }
    
    /*
     * Retourne tous les Etablissements
     * @return type
     */
    public function getAllEtablissement() {
        $qb = $this->createQueryBuilder('e')
                ->where('e.etatEtablissement != ' . TypeEtat::SUPPRIME);
               // ->orderBy('e.typeEtablissement', 'ASC');
        return $qb->getQuery()->getResult();
    }
    /*
     * Retourne tous les profils
     * @return type
     */
    public function getAllActifEtablissement() {
        $qb = $this->createQueryBuilder('e')
                ->where('e.etatEtablissement = ' . TypeEtat::ACTIF);
               // ->orderBy('e.typeEtablissement', 'ASC');
        return $qb->getQuery()->getResult();
    }
    /*
     * Retourne tous les profils
     * @return type
     */
    public function getAllActifEtablissementAccueil() {
        $qb = $this->createQueryBuilder('e')
                ->where('e.etatEtablissement = ' . TypeEtat::ACTIF)
                ->andWhere('e.id != ' . TypeEtat::ACTIF);
               // ->orderBy('e.typeEtablissement', 'ASC');
        return $qb->getQuery()->getResult();
    }
    
}
