<?php

namespace admin\ScolariteBundle\Entity;

/**
 * FaireCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaireCoursRepository extends \Doctrine\ORM\EntityRepository
{
}
