<?php

namespace admin\ScolariteBundle\Entity;
use \admin\UserBundle\Types\TypeEtat;

/**
 * FiliereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiliereRepository extends \Doctrine\ORM\EntityRepository
{
        /*
     * Retourne un ou tous les profils si $idFiliere = 0
     * @param int $idFiliere
     * @return array
     */
    public function getAllOrOneFiliere($idFiliere) {
        $idFiliereQuery = (int) $idFiliere;
        $qb = $this->createQueryBuilder('p')
                ->where('p.etatFiliere != ' . TypeEtat::SUPPRIME)
                ;
        if($idFiliere > 0){
            $qb->andWhere('p.id =:idFiliere')
                    ->setParameter('idFiliere', $idFiliereQuery);
            
        }
        return $qb->getQuery()->getResult();
    }
    
    /*
     * Retourne tous les profils
     * @return type
     */
    public function getAllFiliere() {
        $qb = $this->createQueryBuilder('e')
                ->where('e.etatFiliere != ' . TypeEtat::SUPPRIME);
               // ->orderBy('e.typeFiliere', 'ASC');
        return $qb->getQuery()->getResult();
    }
    /*
     * Retourne tous les profils
     * @return type
     */
    public function getAllActifFiliere() {
        $qb = $this->createQueryBuilder('e')
                ->where('e.etatFiliere = ' . TypeEtat::ACTIF);
               // ->orderBy('e.typeFiliere', 'ASC');
        return $qb->getQuery()->getResult();
    }
    
}
