<?php

namespace admin\ScolariteBundle\Entity;

/**
 * HeureCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeureCoursRepository extends \Doctrine\ORM\EntityRepository
{
}
