<?php

namespace admin\ScolariteBundle\Entity;

/**
 * HeureJourneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeureJourneeRepository extends \Doctrine\ORM\EntityRepository
{
}
