<?php

namespace admin\ScolariteBundle\Entity;
use \admin\UserBundle\Types\TypeEtat;


/**
 * JourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JourRepository extends \Doctrine\ORM\EntityRepository
{
        /*
     * Retourne un ou tous les profils si $idJour = 0
     * @param int $idJour
     * @return array
     */
    public function getAllOrOneJour($idJour) {
        $idJourQuery = (int) $idJour;
        $qb = $this->createQueryBuilder('p')
                ->where('p.etatJour != ' . TypeEtat::SUPPRIME)
                ;
        if($idJour > 0){
            $qb->andWhere('p.id =:idJour')
                    ->setParameter('idJour', $idJourQuery);
            
        }
        return $qb->getQuery()->getResult();
    }
    
    /*
     * Retourne tous les profils
     * @return type
     */
    public function getAllJour() {
        $qb = $this->createQueryBuilder('e')
                ->where('e.etatJour != ' . TypeEtat::SUPPRIME);
               // ->orderBy('e.typeJour', 'ASC');
        return $qb->getQuery()->getResult();
    }
}
