<?php

namespace admin\ScolariteBundle\Entity;
use \admin\UserBundle\Types\TypeEtat;

/**
 * MatiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereRepository extends \Doctrine\ORM\EntityRepository
{
    use \admin\UserBundle\ControllerModel\paramUtilTrait;
         /*
     * Retourne un ou tous les  matieres si $idMatiere = 0
     * @param int $idMatiere
     * @return array
     */
    public function getAllOrOneMatiere($idMatiere) {
        $idMatiereQuery = (int) $idMatiere;
        $qb = $this->createQueryBuilder('p')
                ->where('p.etatMatiere != ' . TypeEtat::SUPPRIME)
                ;
        if($idMatiere > 0){
            $qb->andWhere('p.id =:idMatiere')
                    ->setParameter('idMatiere', $idMatiereQuery);
            
        }
        return $qb->getQuery()->getResult();
    }
    
    /*
     * Retourne tous les  matieres
     * @return type
     */
//    public function getAllMatiere() {
//        $qb = $this->createQueryBuilder('e')
//                ->where('e.etatMatiere != ' . TypeEtat::SUPPRIME);
//               // ->orderBy('e.typeMatiere', 'ASC');
//        return $qb->getQuery()->getResult();
//    }
    
    public function getAllMatiere() {
    $sql =  ' SELECT DISTINCT d.id, d.libelleMatiere, d.etatMatiere, d.descriptionMatiere '
                   .' FROM '.$this->scolariteBundle.'Matiere d '
                   .' WHERE  d.etatMatiere != :cid '
                   .' ORDER BY d.libelleMatiere DESC';

            $query = $this->_em->createQuery($sql);
            $query->setParameter('cid', 2);
            return $query->getResult();
    }     
    
    /*
     * Retourne tous les  matieres
     * @return type
     */
//    public function getAllActifMatiere() {
//        $qb = $this->createQueryBuilder('e')
//                ->where('e.etatMatiere = ' . TypeEtat::ACTIF);
//       return $qb->getQuery()->getResult();
//    }
    
    public function getAllActifMatiere() {
    $sql =  ' SELECT DISTINCT d.id, d.libelleMatiere, d.etatMatiere, d.descriptionMatiere '
                   .' FROM '.$this->scolariteBundle.'Matiere d '
                   .' WHERE  d.etatMatiere = :cid '
                   .' ORDER BY d.libelleMatiere DESC';

            $query = $this->_em->createQuery($sql);
            $query->setParameter('cid', 1);
            return $query->getResult();
    } 
    
    //Recuperer les matieres d'une classe
   public function getAllActifMatiereClasse($idClasse) {
     $sql =  ' SELECT DISTINCT m.id, m.libelleMatiere, m.etatMatiere, m.descriptionMatiere '
                   .' FROM '.$this->scolariteBundle.'Matiere m '
                   .' INNER JOIN m.estenseignes e '
                   .' INNER JOIN e.fairecourss f '
                   .' INNER JOIN f.classe c '
                   .' WHERE  m.etatMatiere = :cid and c.id =:idClasse'
                   .' ORDER BY m.libelleMatiere DESC';

            $query = $this->_em->createQuery($sql);
            $query->setParameters(array('cid'=> 1, 'idClasse'=>$idClasse));
            return $query->getResult();
    } 
}
