<?php

namespace admin\ScolariteBundle\Entity;

/**
 * RecapMoyenneGeneraleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecapMoyenneGeneraleRepository extends \Doctrine\ORM\EntityRepository
{
   use \admin\UserBundle\ControllerModel\paramUtilTrait;
    public function getRecapNotesEleve($iddecoupe,$etabl=0,$anneeSco=0,$setrouver=0) {
        $dql = "SELECT r FROM " . $this->scolariteBundle . "RecapMoyenneGenerale r "
                . " INNER JOIN r.decoupage d "
                . " INNER JOIN r.setrouver s "
                . " INNER JOIN s.eleve e "
                . " INNER JOIN s.anneescolaire a "
                . " INNER JOIN e.etablissement et "
                . "WHERE d.id =:iddecoup and a.id =:idannee and et.id =:idetabl ";
        
        
        if($setrouver!=0){
             $dql .=  " and s.id =:idsetr ";
             
        }
		
       $query = $this->_em->createQuery($dql);
	   //var_dump($query->getSql());exit;
        $query->setParameter('iddecoup', $iddecoupe);
        $query->setParameter('idannee', $anneeSco);
        $query->setParameter('idetabl', $etabl);
		 if($setrouver!=0){
			$query->setParameter('idsetr',$setrouver);
		}
		
        return $query->getResult();
    } 
    
    
}
