<?php

namespace admin\ScolariteBundle\Entity;

/**
 * RecapNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecapNoteRepository extends \Doctrine\ORM\EntityRepository
{
    
}
