<?php

namespace admin\ScolariteBundle\Entity;

/**
 * SeTrouverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeTrouverRepository extends \Doctrine\ORM\EntityRepository
{
}
