<?php

namespace admin\ScolariteBundle\Entity;

/**
 * TypeExamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeExamenRepository extends \Doctrine\ORM\EntityRepository
{
           use \admin\UserBundle\ControllerModel\paramUtilTrait;
             /*
     * Retourne un ou tous les type examens si $idTypeExamen = 0
     * @param int $idTypeExamen
     * @return array
     */
    public function getAllOrOneTypeExamen($idTypeExamen) {
        $idTypeExamenQuery = (int) $idTypeExamen;
        $qb = $this->createQueryBuilder('p')
                ->where('p.etatTypeExamen != ' . TypeEtat::SUPPRIME)
                ;
        if($idTypeExamen > 0){
            $qb->andWhere('p.id =:idTypeExamen')
                    ->setParameter('idTypeExamen', $idTypeExamenQuery);
            
        }
        return $qb->getQuery()->getResult();
    }
    
    /*
     * Retourne tous les type examens
     * @return type
     */
    public function getAllTypeExamen() {
        $qb = $this->createQueryBuilder('e')
                ->where('e.etatTypeExamen != ' . TypeEtat::SUPPRIME);
        return $qb->getQuery()->getResult();
    }
    
    
    /*
     * Retourne tous les type examens actifs
     * @return type
     */
//    public function getAllActifTypeExamen() {
//        $qb = $this->createQueryBuilder('e')
//                ->where('e.etatTypeExamen = ' . TypeEtat::ACTIF);
//        return $qb->getQuery()->getResult();
//    }
   public function getAllActifTypeExamen() {
    $sql =  ' SELECT DISTINCT d.id, d.libelleTypeExamen, d.etatTypeExamen, d.descriptionTypeExamen '
                   .' FROM '.$this->scolariteBundle.'TypeExamen d '
                   .' WHERE  d.etatTypeExamen = :cid '
                   .' ORDER BY d.libelleTypeExamen DESC';

            $query = $this->_em->createQuery($sql);
            $query->setParameter('cid', 1);
            return $query->getResult();
    }      
 
    
}
