<?php

namespace admin\ScolariteBundle\Entity;
use \admin\UserBundle\Types\TypeEtat;

/**
 * TypeTypeMatiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeMatiereRepository extends \Doctrine\ORM\EntityRepository
{
        use \admin\UserBundle\ControllerModel\paramUtilTrait;
             /*
     * Retourne un ou tous les type matieres si $idTypeMatiere = 0
     * @param int $idTypeMatiere
     * @return array
     */
    public function getAllOrOneTypeMatiere($idTypeMatiere) {
        $idTypeMatiereQuery = (int) $idTypeMatiere;
        $qb = $this->createQueryBuilder('p')
                ->where('p.etatTypeMatiere != ' . TypeEtat::SUPPRIME)
                ;
        if($idTypeMatiere > 0){
            $qb->andWhere('p.id =:idTypeMatiere')
                    ->setParameter('idTypeMatiere', $idTypeMatiereQuery);
            
        }
        return $qb->getQuery()->getResult();
    }
    
    /*
     * Retourne tous les type matieres
     * @return type
     */
    public function getAllTypeMatiere() {
        $qb = $this->createQueryBuilder('e')
                ->where('e.etatTypeMatiere != ' . TypeEtat::SUPPRIME);
        return $qb->getQuery()->getResult();
    }
    
    
    /*
     * Retourne tous les type matieres actifs
     * @return type
     */
//    public function getAllActifTypeMatiere() {
//        $qb = $this->createQueryBuilder('e')
//                ->where('e.etatTypeMatiere = ' . TypeEtat::ACTIF);
//        return $qb->getQuery()->getResult();
//    }
   public function getAllActifTypeMatiere() {
    $sql =  ' SELECT DISTINCT d.id, d.libelleTypeMatiere, d.etatTypeMatiere, d.descriptionTypeMatiere '
                   .' FROM '.$this->scolariteBundle.'TypeMatiere d '
                   .' WHERE  d.etatTypeMatiere = :cid '
                   .' ORDER BY d.libelleTypeMatiere DESC';

            $query = $this->_em->createQuery($sql);
            $query->setParameter('cid', 1);
            return $query->getResult();
    } 
    
    
   public function getClasseTypeMatiere($idNiveau, $idFiliere) {
    $sql =  ' SELECT DISTINCT d.id, d.libelleTypeMatiere, d.etatTypeMatiere, d.descriptionTypeMatiere '
                   .' FROM '.$this->scolariteBundle.'TypeMatiere d '
                   .' INNER JOIN d.estenseignes e '
                   .' INNER JOIN e.filiere f '
                   .' INNER JOIN e.niveau n '
                   .' WHERE  f.id = :idfiliere and  n.id = :idniveau '
                   .' ORDER BY d.id ASC';

            $query = $this->_em->createQuery($sql);
            $query->setParameters(array('idfiliere'=>$idFiliere, 'idniveau'=>$idNiveau));
            return $query->getResult();
    }      
    
}
