<?php

namespace admin\CmsBundle\Repository;
use \admin\UserBundle\Types\TypeEtat;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    
       /*
     * Retourne un ou tous les profils si $idPage = 0
     * @param int $idPage
     * @return array
     */
    public function getAllOrOnePage($idPage) {
        $idPageQuery = (int) $idPage;
        $qb = $this->createQueryBuilder('p')
                ->where('p.etatPage != ' . TypeEtat::SUPPRIME)
                ;
        if($idPage > 0){
            $qb->andWhere('p.id =:idPage')
                    ->setParameter('idPage', $idPageQuery);
            
        }
        return $qb->getQuery()->getResult();
    }
    
    /*
     * Retourne tous les profils
     * @return type
     */
    public function getAllPage() {
        $qb = $this->createQueryBuilder('e')
                ->where('e.etatPage != ' . TypeEtat::SUPPRIME);
        return $qb->getQuery()->getResult();
    }
    /*
     * Retourne tous les profils
     * @return type
     */
    public function getAllPageTemplate($idTemplate) {
        $qb = $this->createQueryBuilder('e')
                ->innerJoin('e.template', 'p')
                ->where('e.etatPage != ' . TypeEtat::SUPPRIME)
                ->andWhere('p.id = ' .$idTemplate );
        return $qb->getQuery()->getResult();
    }
}
