<?php

namespace admin\CmsBundle\Repository;
use \admin\UserBundle\Types\TypeEtat;

/**
 * TemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateRepository extends \Doctrine\ORM\EntityRepository
{
        /*
     * Retourne un ou tous les profils si $idTemplate = 0
     * @param int $idTemplate
     * @return array
     */
    public function getAllOrOneTemplate($idTemplate=0) {
        $idTemplateQuery = (int) $idTemplate;
        $qb = $this->createQueryBuilder('p')
                
                ;
        if($idTemplate > 0){
            $qb->andWhere('p.id =:idTemplate')
                    ->setParameter('idTemplate', $idTemplateQuery);
            
        }else{
            $qb->where('p.etatTemplate != ' . TypeEtat::SUPPRIME);
        }
        return $qb->getQuery()->getResult();
    }
    
    /*
     * Retourne tous les profils
     * @return type
     */
    public function getAllTemplate() {
        $qb = $this->createQueryBuilder('e')
                ->where('e.etatTemplate != ' . TypeEtat::SUPPRIME);
               // ->orderBy('e.typeTemplate', 'ASC');
        return $qb->getQuery()->getResult();
    }
}
