<?php

namespace admin\CmsBundle\Repository;

/**
 * ZonePointeEtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZonePointeEtablissementRepository extends \Doctrine\ORM\EntityRepository
{
}
