<?php

namespace admin\ParamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FichierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichierRepository extends EntityRepository
{
    
    /*
     * 
     * @var string  $paramBundle
     * Nom du Bundle
     */
    private $paramBundle = 'adminParamBundle:';
    
    /*
     * Retourne les diffrents noeuds avec le nombre de leur occurence
     * @param type $like
     * @return type
     */
    public function getStatFile($idFile) {
        $dql = "SELECT f.node, COUNT(f) as nbre FROM " . $this->$paramBundle . "Fichier GROUP BY f.node WHERE f.id =:id ";
        $query = $this->_em->createQuery($dql);
        $query->setParameter('id', $idFile);
        return $query->getResult();
    }
    
}
