<?php

namespace admin\ParamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LoadProcessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoadProcessRepository extends EntityRepository
{
}
