<?php

namespace admin\ParamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * parametreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamRepository extends EntityRepository
{
}
