<?php

namespace admin\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use \admin\UserBundle\Types\TypeEtat;

/**
 * CodeBaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeBaseRepository extends EntityRepository {


}
