<?php

namespace admin\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnexionRepository extends EntityRepository
{
    
   

    public function getNotLogoutConnexion($idUser){
        $rep = NULL;     
        $connexions =$this->getNotLogoutConnexionUser($idUser);
        if( ($connexions != NULL) && (!empty($connexions)) && (count($connexions) > 0)){  
            $rep = $connexions[count($connexions)-1];
        }
        
        return $rep;
    }
    
        public function getDerniereConnexion($idUser) {
        //$idUserQuery = (int) $idUser;
        $qb = $this->createQueryBuilder('c')                 
                ->leftJoin('c.utilisateur', 'u')
                ->addSelect('u')
               
                ->andWhere('u.id =:id')
                ->setParameter('id', $idUser)
        
                ->orderBy('c.dateConnexion', 'DESC');
        
        return $qb->getQuery()->getResult();
    }
    
    
    public function getNotLogoutConnexionUser($idUser){ 
        $qb = $this->createQueryBuilder('c')
                ->where('c.dateDeconnexion  is NULL ')
                ->leftJoin('c.utilisateur', 'u')
                ->addSelect('u')
               
                ->andWhere('u.id =:id')
                ->setParameter('id', $idUser);
        
        return $qb->getQuery()->getResult();
    }
    
}
