<?php

namespace admin\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use \admin\UserBundle\Types\TypeEtat;
use \admin\UserBundle\Types\TypeCodeProfil;
use \admin\UserBundle\Types\TypeProfil;


/**
 * ProfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilRepository extends EntityRepository {

    /*
     * Retourne tous les profils utilisateurs actifs sauf le superviseur
     * @return type
     */
//    public function getProfilSansSuperviseur() {
//        $qb = $this->createQueryBuilder('p')
//                ->where('p.etat = ' . TypeEtat::ACTIF)
//                ->andWhere('p.code !=:code')
//                ->setParameter('code', TypeCodeProfil::SUPERVISEUR)
//                ->andWhere('p.typeProfil ='. TypeProfil::PROFIL_UTILISATEUR)
//                ->orderBy('p.nom', 'ASC');
//        
//        return $qb->getQuery()->getResult();
//    }
    
    /*
     * Retourne un ou tous les profils si $idProfil = 0
     * @param int $idProfil
     * @return array
     */
    public function getAllOrOneProfil($idProfil) {
        $idProfilQuery = (int) $idProfil;
        $qb = $this->createQueryBuilder('p')
                ->where('p.etat != ' . TypeEtat::SUPPRIME)
                ->orderBy('p.typeProfil', 'ASC');
        if($idProfil > 0){
            $qb->andWhere('p.id =:idProfil')
                    ->setParameter('idProfil', $idProfilQuery);
            
        }
        return $qb->getQuery()->getResult();
    }
    
    /*
     * Retourne tous les profils
     * @return type
     */
    public function getAllProfil() {
        $qb = $this->createQueryBuilder('p')
                ->where('p.etat != ' . TypeEtat::SUPPRIME)
                ->andwhere('p.typeProfil != 4' )
                ->orderBy('p.typeProfil', 'ASC');
        return $qb->getQuery()->getResult();
    }

    
    
}
