<?php

namespace admin\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeAbonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAbonneRepository extends EntityRepository
{
}
