services:
#    admin_economat.example:
#        class: admin\EconomatBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    operation_manager:
        class: admin\EconomatBundle\Services\OperationManager
        arguments: ["@doctrine.orm.entity_manager"]    
        tags: 
            - { name: twig.extension }
