<?php

namespace admin\MessagerieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    private $messagerieBundle = 'adminMessagerieBundle:';

    /*
     * Retourne un tableau des messages ayant le même codeFil, c'est à dire un fil de discussion
     * 
     * @param string $codeTicket
     * @return array
     */
    public function getTickeMessage($codeTicket)
    {
        $dql = 'SELECT m FROM '.$this->messagerieBundle.'Message m WHERE m.codeFil =:codeFil  ';
        $query = $this->_em->createQuery($dql);
        $query->setParameter('codeFil', $codeTicket);

        return $query->getResult();
    }
}
