destinataire:
    path:     /
    defaults: { _controller: "adminParamBundle:Destinataire:index" }

destinataire_show:
    path:     /{id}/show
    defaults: { _controller: "adminParamBundle:Destinataire:show" }

destinataire_new:
    path:     /new
    defaults: { _controller: "adminParamBundle:Destinataire:new" }

destinataire_create:
    path:     /create
    defaults: { _controller: "adminParamBundle:Destinataire:create" }
    methods:  POST

destinataire_edit:
    path:     /{id}/edit
    defaults: { _controller: "adminParamBundle:Destinataire:edit" }

destinataire_update:
    path:     /{id}/update
    defaults: { _controller: "adminParamBundle:Destinataire:update" }
    methods:  [POST, PUT]

destinataire_delete:
    path:     /{id}/delete
    defaults: { _controller: "adminParamBundle:Destinataire:delete" }
    methods:  [POST, DELETE]
