emetteur:
    path:     /
    defaults: { _controller: "adminParamBundle:Emetteur:index" }

emetteur_show:
    path:     /{id}/show
    defaults: { _controller: "adminParamBundle:Emetteur:show" }

emetteur_new:
    path:     /new
    defaults: { _controller: "adminParamBundle:Emetteur:new" }

emetteur_create:
    path:     /create
    defaults: { _controller: "adminParamBundle:Emetteur:create" }
    methods:  POST

emetteur_edit:
    path:     /{id}/edit
    defaults: { _controller: "adminParamBundle:Emetteur:edit" }

emetteur_update:
    path:     /{id}/update
    defaults: { _controller: "adminParamBundle:Emetteur:update" }
    methods:  [POST, PUT]

emetteur_delete:
    path:     /{id}/delete
    defaults: { _controller: "adminParamBundle:Emetteur:delete" }
    methods:  [POST, DELETE]
